version: '3.9'
services:
  gui_load_balancer:
    container_name: gui_load_balancer
    image: gui_load_balancer:latest
    build:
      context: ./gui_load_balancer
    depends_on: 
      - "spring_app_gui"
    volumes:
      - "./gui_load_balancer/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - "public"
    ports: 
      - "9300:80"
  spring_app_gui:
    image: spring_app_gui:latest
    build:
      context: ./gui
    depends_on: 
      - "api_load_balancer"
    networks:
      - "public"
    expose:
      - "80"
  api_load_balancer:
    container_name: api_load_balancer
    image: api_load_balancer:latest
    build:
      context: ./api_load_balancer
    depends_on: 
      - "spring_app_api"
    volumes:
      - "./api_load_balancer/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - "public"
      - "private"
    expose: 
      - "80"
  spring_app_api:
    image: spring_app_api:latest
    build:
      context: ./api
    depends_on: 
      - "app_db"
    volumes:
      - "./volume:/usr/app/storage"
    networks:
      - "private"
    expose:
      - "8080"
  app_db:
    container_name: app_db
    image: app_db:latest
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: app_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    networks:
      - "private"
networks:
  public:
    name: public network
  private:
    name: private network
